-include ../../../../../petscdir.mk
ALL: lib

DIRS      = layout basic map
LOCDIR    = src/sys/classes/mapping/impls/
MANSEC    = Sys
SUBMANSEC = Mapping

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
