-include ../../../../petscdir.mk
#requiresdefine   'PETSC_USE_FORTRAN'

LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc


