-include ../../../../petscdir.mk
#requiresdefine 'PETSC_USE_LOG'

MANSEC	  = Sys
SUBMANSEC = Profiling
LIBBASE	  = libpetscsys
DIRS	  = default nested mpe

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

