#requirespackage 'PETSC_HAVE_KOKKOS'
-include ../../../../../../petscdir.mk

MANSEC    = ML
SUBMANSEC = PetscDA

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
