-include ../../../../petsckdir.mk

ALL: lib

SOURCEC  = vinv.c vecio.c comb.c vecstash.c vecs.c vsection.c projection.c vecglvis.c vecstreams.c
SOURCEF  =
SOURCEH  =
DIRS     = matlab tagger
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
