-include ../../../../petscdir.mk

CLEANFILES = chwirut1 chwirut2 chwirut1f chwirut2f cs1 cs1_taoterm tomography

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
