ALL: lib

SOURCEH   = ../../../../include/petscmapping.h ../../../../include/petsc/private/mappingimpl.h
SOURCEC   =
DIRS      = interface
LOCDIR    = src/sys/classes/mapping
MANSEC    = Sys
SUBMANSEC = Mapping

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
