ALL: lib

SOURCEH   = ../../../../include/petscim.h ../../../../include/petsc/private/imimpl.h \
           ../../../../include/petsc/private/imtrivialimpl.h
SOURCEC   =
DIRS      = interface impls
LOCDIR    = src/sys/classes/mapping
MANSEC    = Sys
SUBMANSEC = Mapping

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
