-include ../../../../../petscdir.mk
#requirespackage    'THIS_IS_BROKEN_BROKEN_STUFF_IS_NEVER_SUPPOSE_TO_BE_IN_PETSC!'
#requirespackage   'PETSC_HAVE_FFTW'
#requiresprecision double

# Set CFLAGS="-DPETSC_DEBUG_USFFT" to turn on debugging output
MANSEC    = DM
SUBMANSEC = DMDA

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
