#requirespackage 'PETSC_HAVE_CUDA'
-include ../../../../../../petscdir.mk

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCECU = landau.cu
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPLEX
LOCDIR   = src/dm/impls/plex/landau/cuda

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
