-include ../../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_DEVICE' 'PETSC_HAVE_SYCL'

MANSEC  = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
