#include <petsctao.h>
/*
Description:   ADMM tomography reconstruction example .
               0.5*||Ax-b||^2 + lambda*g(x)
Reference:     BRGN Tomography Example
*/

static char help[] = "Finds the ADMM solution to the under constraint linear model Ax = b, with regularizer. \n\
                      A is a M*N real matrix (M<N), x is sparse. A good regularizer is an L1 regularizer. \n\
                      We first split the operator into 0.5*||Ax-b||^2, f(x), and lambda*||x||_1, g(z), where lambda is user specified weight. \n\
                      g(z) could be either ||z||_1, or ||z||_2^2. Default closed form solution for NORM1 would be soft-threshold, which is \n\
                      natively supported in admm.c with -tao_admm_regularizer_type soft-threshold. Or user can use regular TAO solver for  \n\
                      either NORM1 or NORM2 or TAOSHELL, with -reg {1,2} \n\
                      Then, we augment both f and g, and solve it via ADMM. \n\
                      D is the M*N transform matrix so that D*x is sparse. \n";

typedef struct {
  PetscInt  M, N, K, reg;
  PetscReal lambda, eps, mumin;
  Mat       A, ATA, H, Hx, D, Hz, DTD, HF;
  Vec       xlb, xub, x, b, xGT; /* observation b, ground truth xGT, the lower bound and upper bound of x*/
} AppCtx;

/*------------------------------------------------------------*/

PetscErrorCode NullJacobian(Tao tao, Vec X, Mat J, Mat Jpre, void *ptr)
{
  PetscFunctionBegin;
  PetscFunctionReturn(PETSC_SUCCESS);
}

PetscErrorCode InitializeUserData(MPI_Comm comm, AppCtx *user)
{
  char        dataFile[PETSC_MAX_PATH_LEN], path[PETSC_MAX_PATH_LEN]; /* Matrix A and vectors b, xGT(ground truth) binary files generated by Matlab. Debug: change from "tomographyData_A_b_xGT" to "cs1Data_A_b_xGT". */
  PetscViewer fd;                                                     /* used to load data from file */
  PetscInt    k, n;
  PetscScalar v;
  PetscBool   flg;

  PetscFunctionBegin;
  PetscCall(PetscOptionsGetString(NULL, NULL, "-path", path, sizeof(path), &flg));
  PetscCheck(flg, comm, PETSC_ERR_USER, "Must specify -path ${DATAFILESPATH}/tao/tomography");
  /* Load the A matrix, b vector, and xGT vector from a binary file. */
  PetscCall(PetscSNPrintf(dataFile, sizeof(dataFile), "%s/tomographyData_A_b_xGT", path));
  PetscCall(PetscViewerBinaryOpen(comm, dataFile, FILE_MODE_READ, &fd));
  PetscCall(MatCreate(comm, &user->A));
  PetscCall(MatSetType(user->A, MATAIJ));
  PetscCall(MatLoad(user->A, fd));
  PetscCall(MatCreateVecs(user->A, &user->xGT, &user->b));
  PetscCall(VecLoad(user->b, fd));
  PetscCall(VecLoad(user->xGT, fd));
  PetscCall(PetscViewerDestroy(&fd));

  PetscCall(MatGetSize(user->A, &user->M, &user->N));

  PetscCall(MatCreate(comm, &user->D));
  PetscCall(MatSetSizes(user->D, PETSC_DECIDE, PETSC_DECIDE, user->N, user->N));
  PetscCall(MatSetFromOptions(user->D));
  PetscCall(MatSetUp(user->D));
  for (k = 0; k < user->N; k++) {
    v = 1.0;
    n = k + 1;
    if (k < user->N - 1) PetscCall(MatSetValues(user->D, 1, &k, 1, &n, &v, INSERT_VALUES));
    v = -1.0;
    PetscCall(MatSetValues(user->D, 1, &k, 1, &k, &v, INSERT_VALUES));
  }
  PetscCall(MatAssemblyBegin(user->D, MAT_FINAL_ASSEMBLY));
  PetscCall(MatAssemblyEnd(user->D, MAT_FINAL_ASSEMBLY));

  PetscCall(VecDuplicate(user->xGT, &user->x));
  PetscCall(VecSetFromOptions(user->x));

  PetscCall(VecDuplicate(user->x, &user->xlb));
  PetscCall(VecDuplicate(user->x, &user->xub));
  PetscCall(VecSet(user->xlb, 0.0));
  PetscCall(VecSet(user->xub, PETSC_INFINITY));

  user->lambda = 1.e-8;
  user->eps    = 1.e-3;
  user->reg    = 2;
  user->mumin  = 5.e-6;

  PetscOptionsBegin(comm, NULL, "Configure separable objection example", "tomographyADMM.c");
  PetscCall(PetscOptionsInt("-reg", "Regularization scheme for z solver (1,2)", "tomographyADMM.c", user->reg, &user->reg, NULL));
  PetscCall(PetscOptionsReal("-lambda", "The regularization multiplier. 1 default", "tomographyADMM.c", user->lambda, &user->lambda, NULL));
  PetscCall(PetscOptionsReal("-eps", "L1 norm epsilon padding", "tomographyADMM.c", user->eps, &user->eps, NULL));
  PetscCall(PetscOptionsReal("-mumin", "Minimum value for ADMM spectral penalty", "tomographyADMM.c", user->mumin, &user->mumin, NULL));
  PetscOptionsEnd();
  PetscFunctionReturn(PETSC_SUCCESS);
}

/*------------------------------------------------------------*/

PetscErrorCode DestroyContext(AppCtx *user)
{
  PetscFunctionBegin;
  PetscCall(MatDestroy(&user->A));
  PetscCall(MatDestroy(&user->ATA));
  PetscCall(MatDestroy(&user->Hx));
  PetscCall(MatDestroy(&user->Hz));
  PetscCall(MatDestroy(&user->HF));
  PetscCall(MatDestroy(&user->D));
  PetscCall(MatDestroy(&user->DTD));
  PetscCall(VecDestroy(&user->xGT));
  PetscCall(VecDestroy(&user->xlb));
  PetscCall(VecDestroy(&user->xub));
  PetscCall(VecDestroy(&user->b));
  PetscCall(VecDestroy(&user->x));
  PetscFunctionReturn(PETSC_SUCCESS);
}

/*------------------------------------------------------------*/

int main(int argc, char **argv)
{
  Tao         tao, misfit;
  PetscReal   v1, v2;
  AppCtx     *user;
  PetscViewer fd;
  char        resultFile[] = "tomographyResult_x";
  MPI_Comm    comm;

  PetscFunctionBeginUser;
  PetscCall(PetscInitialize(&argc, &argv, NULL, help));
  PetscCall(PetscNew(&user));
  comm = PETSC_COMM_WORLD;
  PetscCall(InitializeUserData(comm, user));
  PetscCall(TaoCreate(comm, &tao));
  PetscCall(TaoSetType(tao, TAOADMM));
  PetscCall(TaoSetSolution(tao, user->x));
  /* f(x) + g(x) for parent tao */
  PetscCall(TaoADMMSetSpectralPenalty(tao, 1.));

  /* f(x) = 0.5 * ||Ax-b||_2^2 for misfit tao */
  {
    TaoTerm misfit_term;

    PetscCall(TaoTermCreate(comm, &misfit_term));
    PetscCall(TaoTermSetType(misfit_term, TAOTERMHALFL2SQUARED));
    PetscCall(TaoTermSetSolutionTemplate(misfit_term, user->b));
    PetscCall(TaoTermSetParametersMode(misfit_term, TAOTERM_PARAMETERS_REQUIRED));
    PetscCall(PetscObjectSetOptionsPrefix((PetscObject)misfit_term, "misfit_"));
    PetscCall(TaoSetTerm(tao, 1.0, misfit_term, user->b, user->A));
    PetscCall(TaoTermDestroy(&misfit_term));
  }

  /* g(x) for regularizer tao */
  {
    TaoTerm reg_term;

    PetscCall(TaoTermCreate(comm, &reg_term));
    PetscCall(TaoTermSetType(reg_term, user->reg == 1 ? TAOTERML1 : TAOTERMHALFL2SQUARED));
    PetscCall(TaoTermSetSolutionTemplate(reg_term, user->x));
    PetscCall(TaoTermSetParametersMode(reg_term, TAOTERM_PARAMETERS_NONE));
    PetscCall(PetscObjectSetOptionsPrefix((PetscObject)reg_term, "reg_"));
    PetscCall(TaoAddTerm(tao, NULL, user->lambda, reg_term, NULL, user->reg == 1 ? user->D : NULL));
    PetscCall(TaoTermDestroy(&reg_term));
  }

  PetscCall(TaoADMMSetMinimumSpectralPenalty(tao, user->mumin));
  /* ADMM of the form

     min f(Ax) + g(z)

     s.t. z = Dx */
  PetscCall(TaoADMMSetTermGroups(tao, 1, NULL, PETSC_FALSE /* unmapped */, 1, NULL, PETSC_TRUE /* mapped */));
  PetscCall(TaoSetFromOptions(tao));

  /* Set type for the misfit solver */
  {
    PetscBool is_admm;

    PetscCall(PetscObjectTypeCompare((PetscObject)tao, TAOADMM, &is_admm));
    if (is_admm) {
      PetscCall(TaoADMMGetMisfitSubsolver(tao, &misfit));
      PetscCall(TaoSetVariableBounds(misfit, user->xlb, user->xub));
    } else {
      PetscCall(TaoSetVariableBounds(tao, user->xlb, user->xub));
    }
  }
  PetscCall(TaoSolve(tao));

  /* Save x (reconstruction of object) vector to a binary file, which maybe read from MATLAB and convert to a 2D image for comparison. */
  PetscCall(PetscViewerBinaryOpen(comm, resultFile, FILE_MODE_WRITE, &fd));
  PetscCall(VecView(user->x, fd));
  PetscCall(PetscViewerDestroy(&fd));

  /* compute the error */
  PetscCall(VecAXPY(user->x, -1, user->xGT));
  PetscCall(VecNorm(user->x, NORM_2, &v1));
  PetscCall(VecNorm(user->xGT, NORM_2, &v2));
  PetscCall(PetscPrintf(comm, "relative reconstruction error: ||x-xGT||/||xGT|| = %6.4e.\n", (double)(v1 / v2)));

  /* Free TAO data structures */
  PetscCall(TaoDestroy(&tao));
  PetscCall(DestroyContext(user));
  PetscCall(PetscFree(user));
  PetscCall(PetscFinalize());
  return 0;
}

/*TEST

   build:
      requires: !complex !single !__float128 !defined(PETSC_USE_64BIT_INDICES)

   testset:
      requires: datafilespath
      args: -path ${DATAFILESPATH}/tao/tomography

      test:
         suffix: 1
         args: -lambda 1.e-8 -tao_monitor -tao_type nls -tao_nls_pc_type none

      test:
         suffix: 2
         args: -reg 2 -lambda 1.e-8 -tao_admm_update_type adaptive -tao_max_it 20 -tao_monitor_constraint_norm -admm_sub_0_tao_monitor -admm_sub_1_tao_monitor -admm_sub_0_tao_nls_pc_type none

      test:
         suffix: 3
         args: -reg 1 -lambda 1.e-8 -tao_admm_update_type basic -tao_max_it 20 -tao_monitor_constraint_norm -admm_sub_0_tao_monitor -admm_sub_1_tao_monitor -admm_sub_0_tao_nls_pc_type none

TEST*/
