#include <petscconf.h>
#include <petscgrid.h>
#include "petsc_fermion.h"//TODO: Get rid of
#include <Grid/Grid.h>

WilsonParameters           TheWilsonParameters;
DomainWallParameters       TheDomainWallParameters;
MobiusDomainWallParameters TheMobiusDomainWallParameters;

NAMESPACE_BEGIN(Grid);

template <class vobj>
int PetscToGrid(DM dm, Vec psi, Lattice<vobj> &g_psi)
{
  PetscFunctionBeginUser;
  typedef typename vobj::scalar_object sobj;

  GridBase         *grid   = g_psi.Grid();
  uint64_t          lsites = grid->lSites();
  std::vector<sobj> scalardata(lsites);

  const PetscScalar *psih;
  PetscInt           dim, vStart, vEnd;
  PetscSection       s;

  PetscCall(DMGetDimension(dm, &dim));
  PetscCall(DMGetLocalSection(dm, &s));
  PetscCall(DMPlexGetDepthStratum(dm, 0, &vStart, &vEnd));
  PetscCall(VecGetArrayRead(psi, &psih));

  Integer idx = 0;
  for (PetscInt v = vStart; v < vEnd; ++v, ++idx) {
    PetscInt dof, off;
    PetscCall(PetscSectionGetDof(s, v, &dof));
    PetscCall(PetscSectionGetOffset(s, v, &off));
    ComplexD *g_p = (ComplexD *)&scalardata[idx];
    for (int d = 0; d < 12; d++) {
      double re = PetscRealPart(psih[off + d]);
      double im = PetscImaginaryPart(psih[off + d]);
      g_p[d]    = ComplexD(re, im);
    }
  }

  assert(idx == lsites);
  vectorizeFromLexOrdArray(scalardata, g_psi);
  PetscFunctionReturn(0);
}

template <class vobj>
int GridToPetsc(DM dm, Vec psi, Lattice<vobj> &g_psi)
{
  PetscFunctionBeginUser;
  typedef typename vobj::scalar_object sobj;

  GridBase         *grid   = g_psi.Grid();
  uint64_t          lsites = grid->lSites();
  std::vector<sobj> scalardata(lsites);
  unvectorizeToLexOrdArray(scalardata, g_psi);

  PetscScalar *psih;
  PetscInt     dim, vStart, vEnd;
  PetscSection s;

  PetscCall(DMGetDimension(dm, &dim));
  PetscCall(DMGetLocalSection(dm, &s));
  PetscCall(DMPlexGetDepthStratum(dm, 0, &vStart, &vEnd));
  PetscCall(VecGetArray(psi, &psih));
  Integer idx = 0;
  for (PetscInt v = vStart; v < vEnd; ++v, ++idx) {
    PetscInt dof, off;
    PetscCall(PetscSectionGetDof(s, v, &dof));
    PetscCall(PetscSectionGetOffset(s, v, &off));
    ComplexD *g_p = (ComplexD *)&scalardata[idx];
    for (int d = 0; d < 12; d++) {
      double re     = real(g_p[d]);
      double im     = imag(g_p[d]);
      psih[off + d] = re + im * PETSC_i;
    }
  }
  assert(idx == lsites);
  PetscCall(VecRestoreArray(psi, &psih));
  PetscFunctionReturn(PETSC_SUCCESS);
}

/*
  Sets the Guage links in a DM using the lattice gauge field
  generated by GRID, or from a lattice checkpoint file.
*/
static PetscErrorCode SetGauge_Grid(DM dm, LatticeGaugeField & Umu)
{
  typedef typename LatticeGaugeField::scalar_object sobj;
  GridBase *grid = Umu.Grid();
  uint64_t lsites = grid->lSites();
  std::vector<sobj> scalardata(lsites);
  unvectorizeToLexOrdArray(scalardata,Umu);

  DM           auxDM;
  Vec          auxVec;
  PetscSection s;
  PetscScalar  *id;
  PetscInt     eStart, eEnd;

  PetscFunctionBegin;
  PetscCall(DMGetAuxiliaryVec(dm, NULL, 0, 0, &auxVec));
  PetscCall(VecGetDM(auxVec, &auxDM));
  PetscCall(DMGetLocalSection(auxDM, &s));
  PetscCall(DMPlexGetDepthStratum(dm, 1, &eStart, &eEnd));
  int j=0;
  ColourMatrixD *Grid_p = (ColourMatrixD *)&scalardata[0];
  // Ordering of edges ???
  for (PetscInt i = eStart; i < eEnd; ++i) {
    ColourMatrixD U = Grid_p[j];
    id = (PetscScalar *) &U;
    PetscCall(VecSetValuesSection(auxVec, s, i, id, INSERT_VALUES));
    j++;
  }
  std::cout << " Set "<<j<<" gauge links "<<std::endl;
  std::cout << " Grid lsites "<<lsites<<std::endl;
  PetscCall(VecViewFromOptions(auxVec, NULL, "-gauge_view"));
  PetscFunctionReturn(0);
}

/*
  Set gauge links in d5 according to the specified fermion mass
 */
static PetscErrorCode SetGauge_Grid5D(DM dm, LatticeGaugeField &Umu, PetscInt Ls, PetscReal m)
{
  PetscScalar  idm[9] = {-m, 0., 0., 0., -m, 0., 0., 0., -m};
  PetscScalar  id[9]  = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
  DM           auxDM;
  Vec          auxVec;
  PetscSection s;
  PetscScalar *up;
  PetscInt     eStart, eEnd;

  PetscFunctionBegin;
  typedef typename LatticeGaugeField::scalar_object sobj;
  GridBase                                         *grid   = Umu.Grid();
  uint64_t                                          lsites = grid->lSites();
  std::vector<sobj>                                 scalardata(lsites);
  unvectorizeToLexOrdArray(scalardata, Umu);

  PetscPrintf(PETSC_COMM_WORLD, "lsites: %ld\n", lsites);
  PetscCall(DMGetAuxiliaryVec(dm, NULL, 0, 0, &auxVec));
  PetscCall(VecGetDM(auxVec, &auxDM));
  PetscCall(DMGetLocalSection(auxDM, &s));
  PetscCall(DMPlexGetDepthStratum(dm, 1, &eStart, &eEnd));
  ColourMatrixD *Grid_p = (ColourMatrixD *)&scalardata[0];
  for (PetscInt i = eStart; i < eEnd; ++i) {
    int d  = i % 5;
    int s5 = i / 5;
    int ss = s5 % Ls;
    int s4 = s5 / Ls;
    if (d == 0) { // Unit link in s-dim
      if (ss == Ls - 1) {
        PetscCall(VecSetValuesSection(auxVec, s, i, idm, INSERT_VALUES));
      } else {
        PetscCall(VecSetValuesSection(auxVec, s, i, id, INSERT_VALUES));
      }
    } else {
      int           jj = d - 1 + 4 * s4;
      ColourMatrixD U  = Grid_p[jj];
      up               = (PetscScalar *)&U;
      PetscCall(VecSetValuesSection(auxVec, s, i, up, INSERT_VALUES));
    }
  }
  PetscCall(VecViewFromOptions(auxVec, NULL, "-gauge_view"));
  PetscFunctionReturn(PETSC_SUCCESS);
}

/*
  Set DMPlex gauge links with file or a lattice configuration generated with downloadable package GRID
 */
static PetscErrorCode FormGauge(DM dm, GRID_LOAD_TYPE type, PetscBool isPV, PetscInt Ls, PetscBool fixGauge, PetscScalar *transform, const char *filename)
{
  FieldMetaData header;
  DomainWallParameters p;

  PetscFunctionBegin;

  if (Ls) {
    p.M5 = 1.8;
    if (isPV) p.m = 1.0;
    else p.m = 0.001;
    p.Ls = Ls;
  }

  Coordinate            latt_size   = GridDefaultLatt();
  Coordinate            simd_layout = GridDefaultSimd(Nd, vComplexD::Nsimd()); //1 is Nd ?
  Coordinate            mpi_layout  = GridDefaultMpi();
  GridCartesian         GRID(latt_size, simd_layout, mpi_layout);
  GridRedBlackCartesian RBGRID(&GRID);
  std::vector<int>      seeds({1, 2, 3, 4});
  GridParallelRNG       pRNG(&GRID);
  pRNG.SeedFixedIntegers(seeds);
  LatticeGaugeFieldD Umu(&GRID);
  switch (type) {
  case 0:
    SU3::ColdConfiguration(pRNG, Umu);
    break;
  case 1:
    SU3::TepidConfiguration(pRNG, Umu);
    break;
  case 2:
    SU3::HotConfiguration(pRNG, Umu);
    break;
  case 3:
    std::cout << GridLogMessage << "Loading configuration from " << filename << std::endl;
    PetscCheck(filename, MPI_COMM_WORLD, PETSC_ERR_ARG_NULL, "No filename provided for Grid.");
    NerscIO::readConfiguration(Umu, header, filename);
    break;
  default:
    SETERRQ(MPI_COMM_WORLD, PETSC_ERR_ARG_OUTOFRANGE, "No support for type %" PetscInt_FMT, type);
    break;
  }
  LatticeGaugeField   U_GT(&GRID); // Gauge transformed field
  LatticeColourMatrix g(&GRID);    // local Gauge xform matrix
  U_GT = Umu;

  if (fixGauge) {
    Real alpha=0.05;
    LatticeColourMatrix xform(&GRID);
    FourierAcceleratedGaugeFixer<PeriodicGimplR>::SteepestDescentGaugeFix(Umu, xform, alpha, 10000, 1.0e-6, 1.0e-6, true);
  }

  if (Ls) PetscCall(SetGauge_Grid5D(dm, Umu, p.Ls, p.m));//Configures 5D links to I and mI
  else PetscCall(SetGauge_Grid(dm, Umu));
  PetscFunctionReturn(PETSC_SUCCESS);
}

PetscErrorCode CheckWilsonWithGrid(DM dm, Mat M, Vec psi, Vec res, const char *filename)
{
  Coordinate latt_size   = GridDefaultLatt();
  Coordinate simd_layout = GridDefaultSimd(Nd,vComplexD::Nsimd());
  Coordinate mpi_layout  = GridDefaultMpi();

  GridCartesian         GRID(latt_size,simd_layout,mpi_layout);
  GridRedBlackCartesian RBGRID(&GRID);

  std::vector<int> seeds({1,2,3,4});
  GridParallelRNG          pRNG(&GRID);
  pRNG.SeedFixedIntegers(seeds);

  LatticeGaugeFieldD Umu(&GRID);
  PetscCheck(filename && filename[0] != '\0', MPI_COMM_WORLD, PETSC_ERR_ARG_NULL, "No filename provided for Grid.");
  std::cout << GridLogMessage << "Loading configuration from " << filename << std::endl;
  FieldMetaData header;
  NerscIO::readConfiguration(Umu, header, filename);

  std::cout<<"****************************************"<<std::endl;
  std::cout << "Gauge invariance test \n";
  std::cout<<"****************************************"<<std::endl;
  LatticeGaugeField     U_GT(&GRID); // Gauge transformed field
  LatticeColourMatrix   g(&GRID);    // local Gauge xform matrix
  U_GT = Umu;
  ////////////////////////////////////////////////////
  // Wilson test
  ////////////////////////////////////////////////////
  LatticeFermionD    g_src(&GRID);
  LatticeFermionD    g_res(&GRID); // Grid result
  LatticeFermionD    p_res(&GRID); // Petsc result
  LatticeFermionD    diff(&GRID); // Petsc result
  LatticeFermionD    tmp(&GRID);

  PetscToGrid(dm,psi,g_src);

  WilsonParameters *p = GetWilsonParameters();
  RealD mass=-0.92;//hard coded to match example
  WilsonFermionD Dw(U_GT,GRID,RBGRID,mass);


  std::cout << "Setting gauge to Grid "<<std::endl;
  SetGauge_Grid(dm, U_GT);

  std::cout << "Testing Dw "<<std::endl;
  const int ncall = 10;
  const int ncallg = 10;
  RealD t0=usecond();
  for(int i=0;i<ncallg;i++){
    Dw.M(g_src,g_res);
  }
  RealD t1=usecond();
  for(int i=0;i<ncall;i++){
      PetscCall(MatMult(M, psi, res)); // Applies DW
  }
  RealD t2=usecond();
  PetscToGrid(dm,res,p_res);

  diff = p_res - g_res;
  std::cout << "******************************"<<std::endl;
  std::cout << "CheckDwWithGrid Grid  " << norm2(g_res)<<std::endl;
  std::cout << "CheckDwWithGrid Petsc " << norm2(p_res)<<std::endl;
  std::cout << "CheckDwWithGrid diff  " << norm2(diff)<<std::endl;
  std::cout << "Grid  " << (t1-t0)/1000/ncallg <<" ms"<<std::endl;
  std::cout << "Petsc " << (t2-t1)/1000/ncall <<" ms"<<std::endl;
  std::cout << "******************************"<<std::endl;

  Dw.Mdag(g_src,g_res);
  PetscCall(VecZeroEntries(res));
  PetscCall(MatMultTranspose(M, psi, res)); // Applies DW
  PetscToGrid(dm,res,p_res);

  diff = p_res - g_res;

  std::cout << "******************************"<<std::endl;
  std::cout << "CheckDwDagWithGrid Grid  " << norm2(g_res)<<std::endl;
  std::cout << "CheckDwDagWithGrid Petsc " << norm2(p_res)<<std::endl;
  std::cout << "CheckDwDagWithGrid diff  " << norm2(diff)<<std::endl;
  std::cout << "******************************"<<std::endl;
  assert(norm2(diff) < 1.0e-7);
  return 0;
}

PetscErrorCode CheckDwfWithGrid(DM dm, Mat dw, Vec psi, Vec res, const char *filename)
{
  PetscInt dim;
  PetscInt Ls;
  DomainWallParameters p;

  PetscFunctionBegin;
  PetscCall(PetscOptionsGetInt(NULL, NULL, "-Ls", &Ls, NULL));
  p.M5 = 1.8;
  p.m  = 0.001;
  p.Ls = Ls;
  SetDomainWallParameters(&p);

  Coordinate latt_size   = GridDefaultLatt();
  Coordinate simd_layout = GridDefaultSimd(Nd, vComplexD::Nsimd());
  Coordinate mpi_layout  = GridDefaultMpi();

  GridCartesian         GRID(latt_size, simd_layout, mpi_layout);
  GridRedBlackCartesian RBGRID(&GRID);

  std::vector<int> seeds({1, 2, 3, 4});
  GridParallelRNG  pRNG(&GRID);
  pRNG.SeedFixedIntegers(seeds);

  LatticeGaugeFieldD  Umu(&GRID);
  LatticeGaugeField   U_GT(&GRID); // Gauge transformed field
  LatticeColourMatrix g(&GRID);    // local Gauge xform matrix

  PetscCheck(filename && filename[0] != '\0', MPI_COMM_WORLD, PETSC_ERR_ARG_NULL, "No filename provided for Grid.");
  std::cout << GridLogMessage << "Loading configuration from " << filename << std::endl;
  FieldMetaData header;
  NerscIO::readConfiguration(Umu, header, filename);
  U_GT = Umu;

  GridCartesian         *FGrid   = SpaceTimeGrid::makeFiveDimGrid(p.Ls, &GRID);
  GridRedBlackCartesian *FrbGrid = SpaceTimeGrid::makeFiveDimRedBlackGrid(p.Ls, &GRID);

  LatticeFermionD g_src(FGrid);
  LatticeFermionD g_res(FGrid); // Grid result
  LatticeFermionD p_res(FGrid); // Petsc result
  LatticeFermionD diff(FGrid);  // Petsc result

  std::cout << "Setting gauge to Grid for Ls=" << p.Ls << std::endl;

  PetscCall(DMGetDimension(dm, &dim));
  PetscToGrid(dm, psi, g_src);

  DomainWallFermionD DWF(U_GT, *FGrid, *FrbGrid, GRID, RBGRID, p.m, p.M5);

  //DWF.Dhop(g_src,g_res,0); Passes with no 5d term
  RealD t0 = usecond();
  DWF.M(g_src, g_res);
  RealD t1 = usecond();
  PetscCall(MatMult(dw, psi, res));
  RealD t2 = usecond();

  PetscToGrid(dm, res, p_res);

  diff = p_res - g_res;
  //std::cout << "p_res: " << p_res << std::endl;
  //std::cout << "g_res: " << g_res << std::endl;
  //std::cout << "Diff: " << diff << std::endl;
  std::cout << "******************************" << std::endl;
  std::cout << "CheckDwWithGrid Grid  " << norm2(g_res) << std::endl;
  std::cout << "CheckDwWithGrid Petsc " << norm2(p_res) << std::endl;
  std::cout << "CheckDwWithGrid diff  " << norm2(diff) << std::endl;
  std::cout << "Grid  " << t1 - t0 << " us" << std::endl;
  std::cout << "Petsc " << t2 - t1 << " us" << std::endl;
  std::cout << "******************************" << std::endl;

  DWF.Mdag(g_src, g_res);
//  DWF.Dhop(g_src,g_res,1);
  PetscCall(MatMultTranspose(dw, psi, res));
  PetscToGrid(dm, res, p_res);

  diff = p_res - g_res;

  std::cout << "******************************" << std::endl;
  std::cout << "CheckDwDagWithGrid Grid  " << norm2(g_res) << std::endl;
  std::cout << "CheckDwDagWithGrid Petsc " << norm2(p_res) << std::endl;
  std::cout << "CheckDwDagWithGrid diff  " << norm2(diff) << std::endl;
  std::cout << "******************************" << std::endl;
  PetscCheck(norm2(diff) < 1.0e-7, PETSC_COMM_WORLD, PETSC_ERR_ARG_OUTOFRANGE, "Grid check failed.");
  PetscFunctionReturn(PETSC_SUCCESS);
}

static PetscErrorCode InitializeGrid(int argc, char **argv){
    PetscFunctionBegin;
    Grid::Grid_init(&argc, &argv);
    PetscFunctionReturn(PETSC_SUCCESS);
}

static PetscErrorCode FinalizeGrid(){
  PetscFunctionBegin;
  Grid::Grid_finalize();
  PetscFunctionReturn(PETSC_SUCCESS);
}

NAMESPACE_END(Grid);

extern "C" {
/*
    Sets Gauge links by using grid. Supported types are cold, tepid, and hot lattice configurations
    as well as checkpointed lattice files.
  */
PetscErrorCode PetscSetGauge_Grid(DM dm, GRID_LOAD_TYPE type, PetscBool isPV, PetscInt Ls, PetscBool fixGauge, PetscScalar *transform, const char *filename)
{
  PetscFunctionBegin;
  PetscCall(Grid::FormGauge(dm, type, isPV, Ls, fixGauge, transform, filename));
  PetscFunctionReturn(PETSC_SUCCESS);
}

PetscErrorCode PetscCheckWilsonWithGrid(DM dm, Mat M, Vec psi, Vec res, const char *filename)
{
  PetscFunctionBegin;
  PetscCall(Grid::CheckWilsonWithGrid(dm, M, psi, res, filename));
  PetscFunctionReturn(PETSC_SUCCESS);
}

PetscErrorCode PetscCheckDwfWithGrid(DM dm, Mat dw, Vec psi, Vec res, const char *filename)
{
  PetscFunctionBegin;
  PetscCall(Grid::CheckDwfWithGrid(dm, dw, psi, res, filename));
  PetscFunctionReturn(PETSC_SUCCESS);
}

PetscErrorCode PetscInitializeGrid(int argc, char **argv)
{
    PetscFunctionBegin;
    PetscCall(Grid::InitializeGrid(argc, argv));
    PetscFunctionReturn(PETSC_SUCCESS);
}

PetscErrorCode PetscFinalizeGrid()
{
  PetscFunctionBegin;
  PetscCall(Grid::FinalizeGrid());
  PetscFunctionReturn(PETSC_SUCCESS);
}
}
