-include ../../../../petscdir.mk
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/ml/regressor/tutorials/
EXAMPLESC       = 
EXAMPLESCXX     =
EXAMPLESF       =
DIRS	          =
MANSEC          = ML
SUBMANSEC       = Regressor

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
