-include ../../../../petscdir.mk

SOURCEC  = pythontao.c
SOURCEH  =
LIBBASE  = libpetsctao
DIRS     =
MANSEC   = Tao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
