-include ../../../../petscdir.mk

SOURCEC  = multiblock.c
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
