ALL: lib

SOURCEH  =
SOURCEC  = mapping.c
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/mapping/interface/
MANSEC   = Mapping

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
