-include ../../../petscdir.mk

SOURCECXX    = check_cxx.cxx
SOURCEF      = check_f.F
SOURCEF90    = check_f90.F90
SOURCECU     = check_cu.cu
SOURCEHIP    = check_hip.hip.cpp
SOURCESYCL   = check_sycl.sycl.cxx
SOURCEKOKKOS = check_kokkos.kokkos.cxx
MANSEC       = Sys
LIBBASE      = libpetscsys
LOCDIR       = src/sys/buildsystem/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

