ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  = utility.c
SOURCECXX = dcontext.cxx device.cxx devicereg.cxx managedtype.cxx
SOURCEF	  =
SOURCEH   = objpool.hpp cupmdevice.hpp sycldevice.hpp hostdevice.hpp managedtype.inl
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/objects/device/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

