-include ../../../../petscdir.mk
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/ml/regressor/tests/
EXAMPLESC       = ex1.c ex2.c ex3.c ex_sharks.c
EXAMPLESCXX     =
EXAMPLESF       =
DIRS	          =
MANSEC          = ML
SUBMANSEC       = Regressor

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
