#include <petsc/private/cupmblasinterface.hpp>

namespace Petsc
{

namespace Impl
{

#define PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_IF_HAVE_EXACT_0(PREFIX,ORIGINAL,MAPPED)
#define PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_IF_HAVE_EXACT_1(PREFIX,ORIGINAL,MAPPED) \
  const decltype(ORIGINAL) CUPMBlasInterface<CUPMDeviceType::PREFIX>::MAPPED;

#define PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_IF_HAVE_EXACT(HAVE,PREFIX,ORGINAL,MAPPED) \
  CAT(PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_IF_HAVE_EXACT_,HAVE)(PREFIX,ORGINAL,MAPPED)

#define PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_EXACT_(PREFIX,ORGINAL,MAPPED) \
  PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_IF_HAVE_EXACT(PetscDefined(CAT(HAVE_,PREFIX)),PREFIX,ORGINAL,MAPPED)

// in case either one or the other don't agree on a name, you can specify all three here
#define PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_EXACT(CUORIGINAL,HIPORIGINAL,MAPPED) \
  PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_EXACT_(CUDA,CAT(CUBLAS,CUORIGINAL),CAT(CUPMBLAS,MAPPED)) \
  PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_EXACT_(HIP,CAT(HIPBLAS,HIPORIGINAL),CAT(CUPMBLAS,MAPPED))

// if both cuda and hip agree on the same name
#define PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE(STEM)             \
  PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE_EXACT(STEM,STEM,STEM)

PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE(_STATUS_SUCCESS)
PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE(_STATUS_NOT_INITIALIZED)
PETSC_CUPMBLAS_DEFINE_STATIC_VARIABLE(_STATUS_ALLOC_FAILED)

} // namespace Impl

} // namespace Petsc
