-include ../../../../petscdir.mk

SOURCEC  = dmfield.c dmfieldregi.c dlregisdmfield.c
SOURCEH  =
DIRS     =
LIBBASE  = libpetscdm
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
