-include ../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_EXODUSII'

CFLAGS    = ${EXODUSII_INCLUDE}
MANSEC    = DM
SUBMANSEC = DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
