#requiresdefine 'PETSC_HAVE_CXX_DIALECT_CXX11'
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCECXX =
SOURCEF   =
SOURCEH   = veccupm.hpp
LIBBASE   = libpetscvec
MANSEC    = Vec
LOCDIR    = src/vec/vec/impls/seq/seqcupm/
DIRS      = cuda

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

