-include ../../../../../../petscdir.mk
#requirespackage 	'PETSC_HAVE_FORTRAN'

SOURCEC = zbrgnf.c
DIR     =
LIBBASE = libpetsctao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
