-include ../../../../petscdir.mk
#requiresdefine   'PETSC_USE_FORTRAN'

MANSEC   = Sys
LIBBASE  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
