# -*- makefile -*-

EXECUTABLE=poisson3d

-include ../../../../../petscdir.mk
-include ${PETSC_DIR}/lib/petsc/conf/variables

.PHONY:all
all: ${EXECUTABLE}.exe

SOURCEC=${EXECUTABLE}.c
SOURCEF=del2lib.f90

OBJSC=${SOURCEC:.c=.o}
OBJSF=${SOURCEF:.f90=.o}

	${PETSC_FCOMPILE}
	${PETSC_COMPILE}
	${CLINKER} -o $@ ${OBJSC} ${OBJSF} ${PETSC_TS_LIB}
	${RM} ${OBJSC} ${OBJSF}

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

OBJSC=${SOURCEC:.c=.o}
OBJSF=${SOURCEF:.f90=.o}
