-include ../../../../../petscdir.mk

MANSEC    = DM
SUBMANSEC = DMPlex

SOURCEKOKKOS = plexlocalizationletkf.kokkos.cxx
LIBBASE      = libpetscdm

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
