-include ../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = regressor.c regressorregi.c dlregisregressor.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscml
MANSEC    = ML
SUBMANSEC = Regressor
LOCDIR    = src/ml/regressor/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
