#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 23 14:09:21 2020

@author: jacobfaibussowitsch
"""
import os

petscDir = os.getenv("PETSC_DIR")
imDir = os.path.join(petscDir, "src", "docs", "website", "images")
if not os.path.exists(imDir):
    raise RuntimeError("Image directory "+imDir+" has moved or been deleted!")

ownerURL = "https://gitlab.com/api/v4/groups/petsc/members/all"
integratorURL = "https://gitlab.com/api/v4/groups/5583565/members/all"
devURL = "https://gitlab.com/api/v4/groups/5981367/members/all"

emeritus = {
    50 : {
        "Lois Curfman McInnes" : ["https://press3.mcs.anl.gov/curfman/", os.path.join(imDir, "lois.gif")],
        "William Gropp" : ["https://cs.illinois.edu/directory/profile/wgropp", os.path.join(imDir, "bill.gif")],
        "Victor Eijkhout" : ["https://www.tacc.utexas.edu/staff/victor-eijkhout", os.path.join(imDir, "victor.jpg")],
        "Peter Brune" : ["", os.path.join(imDir, "peter.jpg")],
        "Kris Buschelman" : ["", os.path.join(imDir, "buschelman.jpg")],
        "Sean Farley" : ["https://farley.io/", os.path.join(imDir, "sean.jpg")],
        "Dmitry Karpeev" : ["https://www.ci.uchicago.edu/profile/224", os.path.join(imDir, "dmitry.jpg")],
        "Dinesh Kaushik" : ["", os.path.join(imDir, "dinesh.jpg")],
        "Jason Sarich" : ["https://www.anl.gov/mcs/person/jason-sarich", os.path.join(imDir, "sarich.jpg")],
        "Victor Minden" : ["", os.path.join(imDir, "victorminden.jpg")]
    }
}

def getJson(url, token):
    import requests

    headers = {"PRIVATE-TOKEN": token}
    r = requests.get(url, headers = headers)
    r.raise_for_status()
    return r.json()

def extractLists(devs):
    tierDict = {}
    for dev in devs:
        alevel = dev["access_level"]
        if alevel not in tierDict:
            tierDict[alevel] = {}
        tierDict[alevel][dev["name"]] = [dev["web_url"], dev["avatar_url"]]
    return tierDict

def writeRst(fname, devs):
    with open(fname, "w+") as f:
        f.writelines([
            ".. raw:: html\n\n",
            "   <!-- Generated by generate_authors_table.py -->\n",
            "   <div class=\"petsc-team-container\">\n",
            "   <style>\n",
            "     img.avatar {border-radius: 10px;width: 60px;height: 60px;}\n",
            "   </style>\n"
        ])
        lines = []
        for level in sorted(devs, reverse = True):
            for dev in sorted(devs[level], key = lambda x: x.split(" ")[-1]):
                lines.append("    <div>\n")
                lines.append("    <a href='%s'><img src='%s' class='avatar' /></a> <br />\n" %
                             (devs[level][dev][0], devs[level][dev][1]))
                lines.append("    <p>%s</p>\n" % (dev))
                lines.append("    </div>\n")
        lines.append("    </div>\n")
        f.writelines(lines)
    print("Wrote table to "+fname)

if __name__ == "__main__":
    import argparse
    import pathlib
    import os

    string = "<string>"
    path = "<path/to/dir>"
    parser = argparse.ArgumentParser(description = "Build Developer Table", formatter_class = argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-t", "--gitlab-token", required = True, metavar = string, help = "Specify your private Gitlab Authentican Token", dest = "token")
    parser.add_argument("-o", "--output-dir", required = True, metavar = path, type = pathlib.Path, help = "Specify the output directory", dest = "writeDir")
    args = parser.parse_args()
    devJson = getJson(devURL, args.token)
    ownerJson = getJson(ownerURL, args.token)
    integratorJson = getJson(integratorURL, args.token)
    megaJson = devJson+ownerJson+integratorJson
    tierlist = extractLists(megaJson)
    writeDir = args.writeDir
    if not os.path.exists(writeDir):
        os.makedirs(writeDir)
    currentFile = os.path.join(writeDir, "petsc-team-table.inc")
    writeRst(currentFile, tierlist)
    emeritusFile = os.path.join(writeDir, "petsc-emeritus-table.inc")
    writeRst(emeritusFile, emeritus)
