-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = basic.c
SOURCEF   =
SOURCEH   =
MANSEC    = Sys
SUBMANSEC = Mapping
LIBBASE   = libpetscsys
DIRS      =
LOCDIR    = src/sys/classes/mapping/impls/basic/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
