-include ../../../../petscdir.mk

LIBBASE        = libpetscsnes
MANSEC         = DM
BFORTSUBMANSEC = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

