-include ../../../petscdir.mk

SOURCEC  = snesmfj.c
SOURCEH  =
LIBBASE  = libpetscsnes
MANSEC   = SNES
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

