
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = graph.c
SOURCECXX = graph_cxx.cxx
SOURCEF   =
SOURCEH   =
MANSEC    = Sys
LIBBASE   = libpetscsys
LOCDIR    = src/sys/objects/graph/interface/
DIRS      =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

