-include ../../../../../petscdir.mk
ALL: lib

SOURCEC  = linear.c
SOURCEH  = linearimpl.h
LIBBASE  = libpetscml
DIRS     =
MANSEC   = ML
LOCDIR   = src/ml/regressor/impls/linear

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


