#!/usr/bin/env python3
"""Add links to examples that use symbols documented in manual pages."""

import os
import re
from collections import Counter


_MAX_EXAMPLES = 10
_SOURCE_SUFFIXES = ('.c', '.cxx', '.F90')
_EXCLUDED_DIRS = {'binding', 'ftn-auto', 'ftn-custom', 'ftn-mod', 'output'}
_CITATION_PATTERN = re.compile(r'man:\+(.*)\+\+(.*)\+\+\+\+man\+\.\./(.*)#.*')
_EXCLUDE_PATTERN = re.compile(
  r'PetscCall|Petsc[A-Z]*Int|PetscReal|PetscScalar|PetscBool|PetscComplex|PetscErrorCode|SETERR|PetscLog|PETSC_FALSE|PETSC_TRUE'
)
_IDENTIFIER_PATTERN = re.compile(r'[A-Za-z_][A-Za-z0-9_]*')
_HELP_PATTERN = re.compile(
  r'\b(?:static\s+)?(?:const\s+)?char\s+help\s*\[[^]]*\]\s*=\s*((?:"(?:\\.|[^"\\])*"\s*)+);', re.DOTALL
)
_LOCATION_PATTERN = re.compile(
  r'## Location\s*<A HREF="PETSC_DOC_OUT_ROOT_PLACEHOLDER/src/([^/]+)/', re.DOTALL
)


# Use main_original() to benchmark against the original implementation.
def processfile_original(petsc_dir,dir,file,keyre,mdict,uses):
  '''Find all functions used in the tutorial and add links to the manual page for the function'''
  #print('Processing '+os.path.join(dir,file))
  with open(os.path.join(dir,file),'r') as fd:
    text = fd.read()
  found = list(set(keyre.findall(text)))
  for i in found:
    if len(uses[i[1:-1]]) < 10:
      uses[i[1:-1]].append(os.path.join(dir,file))

def processdir_original(petsc_dir,dir,keyre,mdict,uses):
  '''Loop over tutorials, call processfile() on each'''
  #print('Processing '+dir)
  for file in os.listdir(dir):
    if os.path.isfile(os.path.join(dir,file)) and (file.endswith('.c') or file.endswith('.cxx') or file.endswith('.F90')): processfile_original(petsc_dir,dir,file,keyre,mdict,uses)

def loadmanualpagescit_original(petsc_dir,build_dir):
  '''Loads and parses the manualpages.cit file generated by Sowing doctext'''
  import re
  mdict = {}
  PATTERN = re.compile(r'man:\+(.*)\+\+(.*)\+\+\+\+man\+\.\./(.*)#.*')
  EXCLUDE_PATTERN = re.compile('PetscCall|Petsc[A-Z]*Int|PetscReal|PetscScalar|PetscBool|PetscComplex|PetscErrorCode|SETERR|PetscLog|PETSC_FALSE|PETSC_TRUE')
  with open(os.path.join(build_dir,'manualpages','manualpages.cit'),'r') as fd:
    text = fd.read()
  for line in  text.split():
    m = re.match(PATTERN, line)
    # print('Manual page '+m.group(1)+' location '+m.group(3))
    if not m:
      raise RuntimeError('Cannot find PATTERN '+str(PATTERN)+' in manualpages.cit line '+line)
    if re.match(EXCLUDE_PATTERN,m.group(1)): continue
    mdict[r' '+m.group(1)+r' '] = m.group(3)
    mdict[r' '+m.group(1)+r'\)'] = m.group(3)
    mdict[r' '+m.group(1)+r','] = m.group(3)
    mdict[r'\('+m.group(1)+r'\('] = m.group(3)
  # sort to find enclosing names first
  mdict = dict(sorted(mdict.items(), key=lambda item: len(item[0]), reverse = True))
  keyre = re.compile('|'.join(list(mdict.keys())))
  uses = {i[1:-1]: [] for i in mdict.keys()}
  return keyre,mdict,uses

def main_original(petsc_dir,build_dir):
    keyre,mdict,uses = loadmanualpagescit_original(petsc_dir,build_dir)
    for dirpath, dirnames, filenames in os.walk(os.path.join(petsc_dir,'src'),topdown=True):
      dirnames[:] = [d for d in dirnames if d not in ['output', 'ftn-custom', 'ftn-auto', 'ftn-mod', 'tests', 'binding']]
      if dirpath.endswith('tutorials'):
        processdir_original(petsc_dir,dirpath,keyre,mdict,uses)

    for i in mdict:
      if len(uses[i[1:-1]]) > 0:
        manpage = os.path.join(build_dir,'manualpages',mdict[i])
        set_uses = set(uses[i[1:-1]])
        uses[i[1:-1]] = []
        with open(manpage,'a') as fd:
          fd.write('\n## Examples\n')
          for j in set_uses:
            file = j.replace(petsc_dir+'/','')
            fd.write('<A HREF="PETSC_DOC_OUT_ROOT_PLACEHOLDER/'+file+'.html">'+file+'</A><BR>\n')


def _manual_page_packages(build_dir, manual_pages):
  """Return the top-level source package that owns each manual page."""
  packages = {}
  section_packages = {}
  for manual_page in sorted(manual_pages):
    with open(os.path.join(build_dir, 'manualpages', manual_page), 'r') as fd:
      match = _LOCATION_PATTERN.search(fd.read())
    package = match.group(1) if match else None
    packages[manual_page] = package
    if package:
      section = manual_page.partition('/')[0]
      section_packages.setdefault(section, Counter()).update([package])

  # Header-defined symbols do not have a src/<package> location. Their manual
  # section's dominant source package supplies the package affinity instead.
  section_defaults = {
    section: min(counts, key=lambda package: (-counts[package], package))
    for section, counts in section_packages.items()
  }
  for manual_page, package in packages.items():
    if package is None:
      packages[manual_page] = section_defaults.get(manual_page.partition('/')[0])
  return packages


def loadmanualpagescit(_petsc_dir, build_dir):
  """Load the symbol-to-manual-page mapping generated by Sowing doctext."""
  entries = []
  with open(os.path.join(build_dir, 'manualpages', 'manualpages.cit'), 'r') as fd:
    text = fd.read()
  for line in text.split():
    match = _CITATION_PATTERN.match(line)
    if not match:
      raise RuntimeError('Cannot find PATTERN ' + str(_CITATION_PATTERN) + ' in manualpages.cit line ' + line)
    symbol = match.group(1)
    if _EXCLUDE_PATTERN.match(symbol):
      continue
    entries.append((symbol, match.group(3)))
  packages = _manual_page_packages(build_dir, {manual_page for _, manual_page in entries})
  return {symbol: (manual_page, packages[manual_page]) for symbol, manual_page in entries}


def _process_file(petsc_dir, path, kind, symbols, candidates):
  """Collect manual-page candidates from one tutorial or test."""
  with open(path, 'r') as fd:
    text = fd.read()
  found = set(_IDENTIFIER_PATTERN.findall(text)).intersection(symbols)
  if not found:
    return

  help_match = _HELP_PATTERN.search(text)
  help_symbols = set()
  if help_match:
    help_symbols = set(_IDENTIFIER_PATTERN.findall(help_match.group(1))).intersection(symbols)

  relative_path = os.path.relpath(path, petsc_dir).replace(os.sep, '/')
  path_parts = relative_path.split('/')
  example_package = path_parts[1] if len(path_parts) > 2 and path_parts[0] == 'src' else None
  for symbol in found:
    manual_page, symbol_package = symbols[symbol]
    # Keep this tuple in policy order; the path is the deterministic tie-breaker.
    priority = (
      0 if symbol_package is not None and symbol_package == example_package else 1,
      0 if kind == 'tutorials' else 1,
      0 if symbol in help_symbols else 1,
      relative_path,
    )
    previous = candidates.setdefault(manual_page, {}).get(relative_path)
    if previous is None or priority < previous:
      candidates[manual_page][relative_path] = priority


def main(petsc_dir, build_dir):
  symbols = loadmanualpagescit(petsc_dir, build_dir)
  candidates = {}
  for dirpath, dirnames, filenames in os.walk(os.path.join(petsc_dir, 'src'), topdown=True):
    dirnames[:] = sorted(d for d in dirnames if d not in _EXCLUDED_DIRS)
    kind = os.path.basename(dirpath)
    if kind not in ('tutorials', 'tests'):
      continue
    for filename in sorted(filenames):
      path = os.path.join(dirpath, filename)
      if os.path.isfile(path) and filename.endswith(_SOURCE_SUFFIXES):
        _process_file(petsc_dir, path, kind, symbols, candidates)

  for manual_page in sorted(candidates):
    ranked = sorted(candidates[manual_page].items(), key=lambda item: item[1])[:_MAX_EXAMPLES]
    with open(os.path.join(build_dir, 'manualpages', manual_page), 'a') as fd:
      fd.write('\n## Examples\n')
      for relative_path, _ in ranked:
        fd.write(
          '<A HREF="PETSC_DOC_OUT_ROOT_PLACEHOLDER/' + relative_path + '.html">' + relative_path + '</A><BR>\n'
        )
