-include ../../../../../../petscdir.mk
#requiresdefine 'PETSC_HAVE_FORTRAN'

SOURCEC = zdcontextf.c
LIBBASE = libpetscsys
MANSEC  = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
