ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = auglag.c auglagutils.c
SOURCEF  =
SOURCEH  = auglag.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/constrained/impls/auglag/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

