-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_HIP'

SOURCEC  =
SOURCEHIP = mhiphost.hip.cpp
SOURCEH  =
MANSEC   = Sys
LIBBASE  = libpetscsys
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
