[build-system]
requires = [
  "cython >= 3",
  "numpy",
  "setuptools",
]
build-backend = "setuptools.build_meta"

#[project.optional-dependencies]
#lint = [
#  "ruff",
#  "cython-lint",
#]

[tool.cython-lint]
ignore = [
  "E125", # continuation line with same indent as next logical line
  "E201", # whitespace after '('
  "E202", # whitespace before ')'
  "E221", # multiple spaces before operator
  "E261", # at least two spaces before inline comment
  "E501", # line too long
  "E701", # multiple statements on one line (colon)
  "E702", # multiple statements on one line (semicolon)
]

[tool.ruff.lint]
select = [
  "A",
  "B",
  "C",
  # "D",
  "E",
  "F",
  "G",
  # "I",
  "S",
  "W",
  "UP",
  # "ARG",
  # "ISC",
  "PIE",
  # "PTH",
  "PYI",
  "RET",
  # "RUF",
  # "TRY",
  "YTT",
]

ignore = [
  "E501",  # Line too long
  "E731",  # Do not assign a `lambda` expression, use a `def`
  "G004",  # Logging statement uses f-string
  "S110",  # `try`-`except`-`pass` detected, consider logging the exception
  "UP015", # [*] Unnecessary open mode parameters
  "C901",  # `function` is too complex
]

[tool.ruff.format]
quote-style = "single"
