#requirespackage 'PETSC_HAVE_KOKKOS_KERNELS'
-include ../../../../../../petscdir.mk

SOURCEC   =
SOURCEKOKKOS = bjkokkos.kokkos.cxx
SOURCEH   =
LIBBASE   = libpetscksp
MANSEC    = KSP
SUBMANSEC = PC

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
