-include ../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_CUDA'

SOURCEC  =
SOURCECU = mcudahost.cu
SOURCEH  =
MANSEC   = Sys
LIBBASE  = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
