#include <petsc/private/fortranimpl.h>
#include <petscdmplex.h>

#if defined(PETSC_HAVE_FORTRAN_CAPS)
#define dmplexgetpointnumbering_ DMPLEXGETPOINTNUMBERING
#elif !defined(PETSC_HAVE_FORTRAN_UNDERSCORE) && !defined(FORTRANDOUBLEUNDERSCORE)
#define dmplexgetpointnumbering_ dmplexgetpointnumbering
#endif

/* Definitions of Fortran Wrapper routines */

/* Autogenerated stub misses const */
PETSC_EXTERN void  dmplexgetpointnumbering_(DM dm, IS *numbering, const PetscBool *ghostMask[], PetscLayout *ownedLayout, PetscLayout *ghostLayout, int *ierr)
{
  *ierr = DMPlexGetPointNumbering(dm,numbering,ghostMask,ownedLayout,ghostLayout);
}
