ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pipecg2.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/cg/pipecg2/

pipecg2: auxillaryfunctions.o

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
