-include ../../../../../../petscdir.mk
#requirespackage  'PETSC_HAVE_EXODUSII'

CFLAGS    = ${PNETCDF_INCLUDE} ${NETCDF_INCLUDE} ${EXODUSII_INCLUDE}
MANSEC    = Sys
SUBMANSEC = Viewer

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
