-include ../../../../../../petscdir.mk

SOURCEC   = drawnull.c
SOURCEH   =
MANSEC    = Sys
SUBMANSEC = Draw
LIBBASE   = libpetscsys
DIRS      =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
