-include ../../../../petscdir.mk
#requiresscalar    real

DIRS     = l2 l1 simplex shell
LIBBASE  = libpetsctao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc

