#!/bin/sh 
#This job should be redirected to small queue
#PBS -N originalex2
#PBS -l select=1:ncpus=24
#PBS -l walltime=00:08:00
#PBS -l place=scatter
#PBS -l accelerator_type="None"
#PBS -V 
. /opt/modules/default/init/sh
cd /mnt/lustre/cds/cdsmanas/petsc/src/ksp/ksp/tutorials

export MPICH_NEMESIS_ASYNC_PROGRESS=1
export MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_GNI_USE_UNASSIGNED_CPUS=enabled
export MPICH_GNI_MAX_EAGER_MSG_SIZE=1536
export MPICH_SMP_SINGLE_COPY_SIZE=1024
export MPICH_USE_DMAPP_COLL=1
export MPICH_SHARED_MEM_COLL_OPT=1

MYN=24
MYM=1000
MYS=1000


aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cg  -pc_type jacobi -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cg  -pc_type jacobi -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cg  -pc_type jacobi -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cg  -pc_type jacobi -m $MYM -n $MYS

aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipecg -pc_type jacobi -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipecg -pc_type jacobi -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipecg -pc_type jacobi -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipecg -pc_type jacobi -m $MYM -n $MYS

aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipelcg  -pc_type jacobi -ksp_pipelcg_pipel 2 -ksp_pipelcg_lmax 2 -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipelcg  -pc_type jacobi -ksp_pipelcg_pipel 2 -ksp_pipelcg_lmax 2 -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipelcg  -pc_type jacobi -ksp_pipelcg_pipel 2 -ksp_pipelcg_lmax 2 -m $MYM -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipelcg  -pc_type jacobi -ksp_pipelcg_pipel 2 -ksp_pipelcg_lmax 2 -m $MYM -n $MYS

aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type pipecg2  -pc_type jacobi -m $MYM  -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type groppcg  -pc_type jacobi -m $MYM  -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type groppcg  -pc_type jacobi -m $MYM  -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type groppcg  -pc_type jacobi -m $MYM  -n $MYS

#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cgs  -pc_type jacobi -m $MYM  -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cgs  -pc_type jacobi -m $MYM  -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cgs  -pc_type jacobi -m $MYM  -n $MYS
#aprun -j 1 -n $MYN -N 24  ./originalex2 -ksp_type cgs  -pc_type jacobi -m $MYM  -n $MYS
