
ALL: lib

CFLAGS    =
FFLAGS    =
CPPFLAGS  =
SOURCEC	  =
SOURCEF	  =
SOURCEH	  = impldevicebase.hpp
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  = cupm sycl host
LOCDIR	  = src/sys/objects/device/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

