-include ../../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_LUSOL'
#requiresscalar    real
#requiresprecision double

SOURCEC  = lusol.c
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
