-include ../../../../petscdir.mk
ALL: lib

DIRS     = linear
LOCDIR   = src/ml/regressor/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


