-include ../../../../../../../petscdir.mk
#requirespackage   'PETSC_HAVE_CUDA'

SOURCECU = matseqdensecuda.cu
LIBBASE  = libpetscmat
MANSEC   = Mat
LOCDIR   = src/mat/impls/dense/seq/cupm/cuda/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
