-include ../../../../petsckdir.mk

SOURCEC	  = bench.c
SOURCEF	  =
SOURCEH	  = ../../../../include/petscbench.h ../../../../include/petsc/private/benchimpl.h
MANSEC	  = Sys
LIBBASE	  = libpetscsys
LOCDIR	  = src/sys/classes/bench/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

