
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   =
SOURCECXX =
SOURCEF   =
SOURCEH   =
MANSEC    = Sys
LIBBASE   = libpetscsys
LOCDIR    = src/sys/objects/graph/
DIRS      = interface

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

