-include ../../../petscdir.mk

MANSEC	  = Sys
SUBMANSEC = Profiling
LIBBASE	  = libpetscsys
DIRS	  = interface handler

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
