-include ../../../../../petscdir.mk

SOURCEC  = alpha1.c alpha2.c
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

