-include ../../../../petscdir.mk

SOURCEC  = submat.c
SOURCEH  =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

