-include ../../../../../petscdir.mk

LIBBASE        = libpetscksp
MANSEC         = Mat
BFORTSUBMANSEC = KSP

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules.doc
