-include ../../../../../../petscdir.mk

SOURCEC   = glvis.c
SOURCEH   =
MANSEC    = Sys
SUBMANSEC = Viewer
LIBBASE   = libpetscsys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
