-include ../../../../../../petscdir.mk

SOURCEC   = dspacesimple.c
LIBBASE   = libpetscdm
DIRS      =
MANSEC    = DM
SUBMANSEC = DUALSPACE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
